apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    orgId: 1
    version: 1

  - name: PostgreSQL
    uid: postgres
    type: postgres
    access: proxy
    url: postgres:5432
    database: fooddelivery
    user: fooddelivery
    secureJsonData:
      password: fooddelivery
    jsonData:
      sslmode: disable
      postgresVersion: 1500
    editable: true
    orgId: 1
    version: 1
